#!/bin/ash

emacs --batch --execute "(package-install 'adaptive-wrap)"
emacs --batch --execute "(package-install 'helm)"
emacs --batch --execute "(package-install 'company)"
emacs --batch --execute "(package-install 'yasnippet)"
emacs --batch --execute "(package-install 'geiser-guile)"
emacs --batch --execute "(package-install 'markdown-mode)"
emacs --batch --execute "(package-install 'web-mode)"
emacs --batch --execute "(package-install 'magit)"
emacs --batch --execute "(package-install 'multiple-cursors)"
emacs --batch --execute "(package-install 'idle-highlight-mode)"
emacs --batch --execute "(package-install 'docker)"
emacs --batch --execute "(package-install 'org-present)"
emacs --batch --execute "(package-install 'visual-fill-column)"
emacs --batch --execute "(package-install 'centaur-tabs)"
emacs --batch --execute "(package-install 'which-key)"
emacs --batch --execute "(package-install 'evil-nerd-commenter)"
wget -O ./mods/restclient.el https://raw.githubusercontent.com/pashky/restclient.el/master/restclient.el
