(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
			 ("melpa-stable" . "https://stable.melpa.org/packages/")
			 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
			 ("gnu" . "https://elpa.gnu.org/packages/"))
      package-archive-priorities '(("melpa" . 1)
				   ("melpa-stable" . 2)
				   ("nongnu" . 3)
				   ("gnu" . 4)))
(package-initialize)

(package-refresh-contents)
(package-install 'drag-stuff)
(package-install 'company)
(package-install 'company-box)
(package-install 'yasnippet)
(package-install 'markdown-mode)
(package-install 'magit)
(package-install 'git-modes)
(package-install 'multiple-cursors)
(package-install 'idle-highlight-mode)
(package-install 'org-present)
(package-install 'visual-fill-column)
(package-install 'evil-nerd-commenter)
(package-install 'crux)
(package-install 'dotenv-mode)
(package-install 'company-shell)
(package-install 'nginx-mode)
(package-install 'company-nginx)
(package-install 'restclient)
(package-install 'company-restclient)
(package-install 'diff-hl)
(package-install 'csv-mode)
(package-install 'rainbow-mode)
(package-install 'embark)
(package-install 'dired-subtree)
(package-install 'nerd-icons)
(package-install 'nerd-icons-dired)
(package-install 'denote)
(package-install 'dape) ;; nie działa w emacs 28
(package-install 'beframe)
(package-install 'pyvenv)
(package-install 'mpv)
(package-install 'editorconfig)
(package-install 'editorconfig-generate)
(package-install 'nsis-mode)
(package-install 'apache-mode)
(package-install 'uuidgen)
(package-install 'helm-fuzzy-find)
(package-install 'lorem-ipsum)
(package-install 'gptel)
(package-install 'emmet-mode)
(package-install 'consult)
(package-install 'gnuplot)
(package-install 'password-generator)
(package-install 'indent-bars)
(package-install 'lingva)
(package-install 'sql-indent)
(package-install 'org-drill)
(nerd-icons-install-fonts t)

;;; setup-emacs.el ends here
