(require 'package)

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
			 ("melpa-stable" . "https://stable.melpa.org/packages/")
			 ("nongnu" . "https://elpa.nongnu.org/nongnu/")
			 ("gnu" . "https://elpa.gnu.org/packages/"))
      package-archive-priorities '(("melpa" . 1)
				   ("melpa-stable" . 2)
				   ("nongnu" . 3)
				   ("gnu" . 4)))
(package-initialize)

(package-install 'docker)
(package-install 'dockerfile-mode)
(package-install 'treemacs)
(package-install 'docker-compose-mode)
(package-install 'css-eldoc)
(package-install 'js-doc)
(package-install 'js2-mode)
(package-install 'tide)
(package-install 'lsp-pascal)
(package-install 'lsp-mode)
(package-install 'lsp-ui)
(package-install 'flymake-ruby)

(lsp-install-server "yamlls")
(lsp-install-server "xmlls")
(lsp-install-server "vue-semantic-server")
(lsp-install-server "html-ls")
(lsp-install-server "nginx-ls")
(lsp-install-server "marksman")
(lsp-install-server "json-ls")
(lsp-install-server "ts-ls")
(lsp-install-server "graphql-lsp")
(lsp-install-server "dockerfile-ls")
(lsp-install-server "css-ls")
(lsp-install-server "bash-ls")
(lsp-install-server "ansible-ls")
