#!/bin/ash

emacs --batch --execute "(package-install 'adaptive-wrap)"
emacs --batch --execute "(package-install 'helm)"
emacs --batch --execute "(package-install 'company)"
emacs --batch --execute "(package-install 'yasnippet)"
emacs --batch --execute "(package-install 'geiser-guile)"
emacs --batch --execute "(package-install 'markdown-mode)"
