(require 'company)
(require 'cl-lib)

(defconst completions
  '(
	#("a" 0 1 (:annotation "Tag" :help "Defines a hyperlink."))
	#("abbr" 0 1 (:annotation "Tag" :help "Defines an abbreviation or an acronym."))
	#("acronym" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use <abbr> instead."))
	#("address" 0 1 (:annotation "Tag" :help "Defines contact information for the author/owner of a document."))
	#("applet" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use <embed> or <object>."))
	#("area" 0 1 (:annotation "Tag" :help "Defines an area inside an image map."))
	#("article" 0 1 (:annotation "Tag" :help "Defines an article."))
	#("aside" 0 1 (:annotation "Tag" :help "Defines content aside from the page content."))
	#("audio" 0 1 (:annotation "Tag" :help "Defines embedded sound content."))
	#("b" 0 1 (:annotation "Tag" :help "Defines bold text."))
	#("base" 0 1 (:annotation "Tag" :help "Specifies the base URL/taret for all relative URLs in a document."))
	#("basefont" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use CSS instead."))
	#("bdi" 0 1 (:annotation "Tag" :help "Isolates a part of text that might be formatted in a different direction from other text outside it."))
	#("bdo" 0 1 (:annotation "Tag" :help "Overrides the current text direction."))
	#("big" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use CSS instead. Defines big text."))
	#("blockquote" 0 1 (:annotation "Tag" :help "Defines a section that is quoted from another source."))
	#("body" 0 1 (:annotation "Tag" :help "Defines the document's body."))
	#("br" 0 1 (:annotation "Tag" :help "Defines a single line break."))
	#("button" 0 1 (:annotation "Tag" :help "Defines a clickable button."))
	#("canvas" 0 1 (:annotation "Tag" :help "Used to draw graphics, on the fly, via scripting."))
	#("caption" 0 1 (:annotation "Tag" :help "Defines a table caption."))
	#("center" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use CSS instead. Defines centered text."))
	#("cite" 0 1 (:annotation "Tag" :help "Defines the title of a work."))
	#("code" 0 1 (:annotation "Tag" :help "Defines a piece of computer code."))
	#("col" 0 1 (:annotation "Tag" :help "Specifies column properties for each column within a <colgroup> element."))
	#("colgroup" 0 1 (:annotation "Tag" :help "Specifies a group of one or more columns in a table for formatting."))
	#("data" 0 1 (:annotation "Tag" :help "Adds a machine-readable translation of a given content."))
	#("datalist" 0 1 (:annotation "Tag" :help "Specifies a list of pre-defined options for input controls."))
	#("dd" 0 1 (:annotation "Tag" :help "Defines a description/value of a term in a description list."))
	#("del" 0 1 (:annotation "Tag" :help "Defines text that has been deleted from a document."))
	#("details" 0 1 (:annotation "Tag" :help "Defines additional details that the user can view or hide."))
	#("dfn" 0 1 (:annotation "Tag" :help "Specifies a term that is going to be defined within the content."))
	#("dialog" 0 1 (:annotation "Tag" :help "Defines a dialog box or window."))
	#("dir" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use <ul> instead. Defines a director list."))
	#("div" 0 1 (:annotation "Tag" :help "Defines a section in a document."))
	#("dl" 0 1 (:annotation "Tag" :help "Defines a description list."))
	#("dt" 0 1 (:annotation "Tag" :help "Defines a term/name in a description list."))
	#("em" 0 1 (:annotation "Tag" :help "Defines emphasized text."))
	#("embed" 0 1 (:annotation "Tag" :help "Defines a container for an external application."))
	#("fieldset" 0 1 (:annotation "Tag" :help "Groups related elements in a form."))
	#("figcaption" 0 1 (:annotation "Tag" :help "Defines a caption for a <figure> element."))
	#("figure" 0 1 (:annotation "Tag" :help "Specifies self-contained content."))
	#("font" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use CSS instead. Defines font, color, and size for text."))
	#("footer" 0 1 (:annotation "Tag" :help "Defines a footer for a document or section."))
	#("form" 0 1 (:annotation "Tag" :help "Defines an HTML form for user input."))
	#("frame" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Defines a window (a frame) in a frameset."))
	#("frameset" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Defines a set of frames."))
	#("h1" 0 1 (:annotation "Tag" :help "Defines HTML headings."))
	#("h2" 0 1 (:annotation "Tag" :help "Defines HTML headings."))
	#("h3" 0 1 (:annotation "Tag" :help "Defines HTML headings."))
	#("h4" 0 1 (:annotation "Tag" :help "Defines HTML headings."))
	#("h5" 0 1 (:annotation "Tag" :help "Defines HTML headings."))
	#("h6" 0 1 (:annotation "Tag" :help "Defines HTML headings."))
	#("head" 0 1 (:annotation "Tag" :help "Contains metadata/information for the document."))
	#("header" 0 1 (:annotation "Tag" :help "Defines a header for a document or section."))
	#("hgroup" 0 1 (:annotation "Tag" :help "Defines a header and related content."))
	#("hr" 0 1 (:annotation "Tag" :help "Defines a thematic change in the content."))
	#("html" 0 1 (:annotation "Tag" :help "Defines the root of an HTML document."))
	#("i" 0 1 (:annotation "Tag" :help "Defines a part of text in an alternate voice or mood."))
	#("iframe" 0 1 (:annotation "Tag" :help "Defines an inline frame."))
	#("img" 0 1 (:annotation "Tag" :help "Defines an image."))
	#("input" 0 1 (:annotation "Tag" :help "Defines an input control."))
	#("ins" 0 1 (:annotation "Tag" :help "Defines a text that has been inserted into a document."))
	#("kbd" 0 1 (:annotation "Tag" :help "Defines keyboard input."))
	#("label" 0 1 (:annotation "Tag" :help "Defines a label for an <input> element."))
	#("legend" 0 1 (:annotation "Tag" :help "Defines a caption for a <fieldset> element."))
	#("li" 0 1 (:annotation "Tag" :help "Defins a list."))
	#("link" 0 1 (:annotation "Tag" :help "Defines the relationship between a document and an external resource."))
	#("main" 0 1 (:annotation "Tag" :help "Specifies the main content of a document."))
	#("map" 0 1 (:annotation "Tag" :help "Defines an image map."))
	#("mark" 0 1 (:annotation "Tag" :help "Defines marked/highlighted text."))
	#("menu" 0 1 (:annotation "Tag" :help "Defines an unordered list."))
	#("meta" 0 1 (:annotation "Tag" :help "Defines metadata about an HTML doucment."))
	#("meter" 0 1 (:annotation "Tag" :help "Defines a scalar measurement within a known range."))
	#("nav" 0 1 (:annotation "Tag" :help "Defines navigation links."))
	#("noframes" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Defines an alternate content for no support frames."))
	#("noscript" 0 1 (:annotation "Tag" :help "Defines an alternate content for users that do not support client-side scripts."))
	#("object" 0 1 (:annotation "Tag" :help "Defines a container for an external application."))
	#("ol" 0 1 (:annotation "Tag" :help "Defines an ordered list."))
	#("optgroup" 0 1 (:annotation "Tag" :help "Defines a group of related options in a drop-down list."))
	#("option" 0 1 (:annotation "Tag" :help "Defines an option in a drop-down list."))
	#("output" 0 1 (:annotation "Tag" :help "Defines the result of a calculation."))
	#("p" 0 1 (:annotation "Tag" :help "Defines a paragraph."))
	#("param" 0 1 (:annotation "Tag" :help "Defines a parameter for an object."))
	#("picture" 0 1 (:annotation "Tag" :help "Defines a container for multiple image resources."))
	#("pre" 0 1 (:annotation "Tag" :help "Defines preformatted text."))
	#("progress" 0 1 (:annotation "Tag" :help "Represents the progress of a task."))
	#("q" 0 1 (:annotation "Tag" :help "Defines a short quotation."))
	#("rp" 0 1 (:annotation "Tag" :help "Defines what to show in browsers that do not support ruby annotations."))
	#("rt" 0 1 (:annotation "Tag" :help "Defines an explanation/pronounciation of characters."))
	#("ruby" 0 1 (:annotation "Tag" :help "Defines a ruby annotation."))
	#("s" 0 1 (:annotation "Tag" :help "Defines text that is no longer correct."))
	#("samp" 0 1 (:annotation "Tag" :help "Defines sample output from a computer program."))
	#("script" 0 1 (:annotation "Tag" :help "Defines a client-side script."))
	#("search" 0 1 (:annotation "Tag" :help "Defines a search section."))
	#("section" 0 1 (:annotation "Tag" :help "Defines a section in a document."))
	#("select" 0 1 (:annotation "Tag" :help "Defines a section in a document."))
	#("samll" 0 1 (:annotation "Tag" :help "Defines smaller text."))
	#("source" 0 1 (:annotation "Tag" :help "Defines multiple media resources for media elements."))
	#("span" 0 1 (:annotation "Tag" :help "Defines a section in a document."))
	#("strike" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use <del> or <s>."))
	#("strong" 0 1 (:annotation "Tag" :help "Defines important text."))
	#("style" 0 1 (:annotation "Tag" :help "Defines style information for a document."))
	#("sub" 0 1 (:annotation "Tag" :help "Defines subscripted text."))
	#("summary" 0 1 (:annotation "Tag" :help "Defines a visible heading for <details> element."))
	#("sup" 0 1 (:annotation "Tag" :help "Defines superscripted text."))
	#("svg" 0 1 (:annotation "Tag" :help "Defines a container for SVG graphics."))
	#("table" 0 1 (:annotation "Tag" :help "Defines a table."))
	#("tbody" 0 1 (:annotation "Tag" :help "Groups the body content in a table."))
	#("td" 0 1 (:annotation "Tag" :help "Defines cell in a table."))
	#("template" 0 1 (:annotation "Tag" :help "Defines a container for content that should be hidden when the page loads."))
	#("textarea" 0 1 (:annotation "Tag" :help "Defines a multiline input control."))
	#("tfoot" 0 1 (:annotation "Tag" :help "Groups the footer content in a table."))
	#("th" 0 1 (:annotation "Tag" :help "Defines a header cell in a table."))
	#("thead" 0 1 (:annotation "Tag" :help "Groups the header content in a table."))
	#("time" 0 1 (:annotation "Tag" :help "Defines a specific time (or datetime)."))
	#("title" 0 1 (:annotation "Tag" :help "Defines a title for the document."))
	#("tr" 0 1 (:annotation "Tag" :help "Defines a row in a table."))
	#("track" 0 1 (:annotation "Tag" :help "Defines text tracks for media elements."))
	#("tt" 0 1 (:annotation "Tag" :help "Not supported in HTML5. Use CSS instead."))
	#("u" 0 1 (:annotation "Tag" :help "Defines some text that is unarticulated and styled differently from normal text."))
	#("ul" 0 1 (:annotation "Tag" :help "Defines an unordered list."))
	#("var" 0 1 (:annotation "Tag" :help "Defines a variable."))
	#("video" 0 1 (:annotation "Tag" :help "Defines embedded video content."))
	#("wbr" 0 1 (:annotation "Tag" :help "Defines a possible line-break."))
	#("!DOCTYPE" 0 1 (:annotation "Tag" :help "Defines document type."))
	))

(defun company-html-annotation (s)
  (format " %s" (get-text-property 0 :annotation s)))

(defun company-html-meta (s)
  (get-text-property 0 :help s))

(defun company-html (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (cl-case command
	(interactive (company-begin-backend 'company-html))
	(prefix (when (looking-back "<\\([a-zA-Z1-6!]+\\)") (match-string 1)))
	(candidates (cl-remove-if-not
				 (lambda (c) (string-prefix-p arg c))
				 completions))
	(meta (company-html-meta arg))
	(annotation (company-html-annotation arg))))

(provide 'company-html)
