(require 'yasnippet)

(yas-define-snippets 'mhtml-mode '(
				   ("hx-boost" "<hx-boost>$0</hx-boost>" "htmx")
				   ("hx-confirm" "<hx-confirm>$0</hx-confirm>" "htmx")
				   ("hx-delete" "<hx-delete>$0</hx-delete>" "htmx")
				   ("hx-disable" "<hx-disable>$0</hx-disable>" "htmx")
				   ("hx-disable-elt" "hx-disable-elt>$0</hx-disable-elt>" "htmx")
				   ("hx-disinherit" "hx-disinherit>$0</hx-disinherit>" "htmx")
				   ("hx-ext" "<hx-ext>$0</hx-ext>" "htmx")
				   ("hx-encoding" "hx-encoding>$0</hx-encoding>" "htmx")
				   ("hx-get" "<hx-get>$0</hx-get>" "htmx")
				   ("hx-header" "<hx-header>$0</hx-header>" "htmx")
				   ("hx-history" "<hx-history>$0</hx-history>" "htmx")
				   ("hx-history-elt" "<hx-history-elt>$0</hx-history-elt>" "htmx")
				   ("hx-include" "<hx-include>$0</hx-include>" "htmx")
				   ("hx-indicator" "<hx-indicator>$0</hx-indicator>" "htmx")
				   ("hx-put" "<hx-put>$0</hx-put>" "htmx")
				   ("hx-push-url" "<hx-push-url>$0</hx-push-url>" "htmx")
				   ("hx-post" "<hx-post>$0</hx-post>" "htmx")
				   ("hx-patch" "<hx-patch>$0</hx-patch>" "htmx")
				   ("hx-params" "<hx-params>$0</hx-params>" "htmx")
				   ("hx-preserve" "<hx-preserve>$0</hx-preserve>" "htmx")
				   ("hx-prompt" "<hx-prompt>$0</hx-prompt>" "htmx")
				   ("hx-replace-url" "<hx-replace-url>$0</hx-replace-url>" "htmx")
				   ("hx-request" "<hx-request>$0</hx-request>" "htmx")
				   ("hx-select" "<hx-select>$0</hx-select>" "htmx")
				   ("hx-select-oob" "<hx-select-oob>$0</hx-select-oob>" "htmx")
				   ("hx-sse" "<hx-sse>$</hx-sse>" "htmx")
				   ("hx-swap" "<hx-swap>$0</hx-swap>" "htmx")
				   ("hx-swap-oob" "<hx-swap-oob>$0</hx-swap-oob>" "htmx")
				   ("hx-sync" "<hx-sync>$0</hx-sync>" "htmx")
				   ("hx-on" "<hx-on>$0</hx-on>" "htmx")
				   ("hx-on:click" "<hx-on:click>$0</hx-on:click>" "htmx")
				   ("hx-on:htmx:validation:validate" "<hx-on:htmx:validation:validate>$0</hx-on:htmx:validation:validate>" "htmx")
				   ("hx-on:htmx:config-request" "<hx-on:htmx:config-request>$0</hx-on:htmx:config-request>" "htmx")
				   ("hx-target" "<hx-target>$0</hx-target>" "htmx")
				   ("hx-trigger" "<hx-trigger>$0</hx-trigger>" "htmx")
				   ("hx-encoding" "<hx-encoding>$0</hx-encoding>" "htmx")
				   ("hx-ws" "<hx-ws>$0</hx-ws>" "htmx")
				   ("hx-vals" "<hx-vals>$0</hx-vals>" "htmx")
				   ("hx-validate" "<hx-validate>$0</hx-validate>" "htmx")
				   ))

(provide 'company-htmx)
