(require 'company)
(require 'cl-lib)

(defconst tag-completions
  '(
	#("a" 0 1 (:annotation "Tag" :help ""))
	#("animate" 0 1 (:annotation "Tag" :help ""))
	#("animateMotion" 0 1 (:annotation "Tag" :help ""))
	#("animateTransform" 0 1 (:annotation "Tag" :help ""))
	#("circle" 0 1 (:annotation "Tag" :help ""))
	#("clipPath" 0 1 (:annotation "Tag" :help ""))
	#("cursor" 0 1 (:annotation "Tag" :help ""))
	#("defs" 0 1 (:annotation "Tag" :help ""))
	#("desc" 0 1 (:annotation "Tag" :help ""))
	#("ellipse" 0 1 (:annotation "Tag" :help ""))
	#("feBlend" 0 1 (:annotation "Tag" :help ""))
	#("feColorMatrix" 0 1 (:annotation "Tag" :help ""))
	#("feComponentTransfer" 0 1 (:annotation "Tag" :help ""))
	#("feComposite" 0 1 (:annotation "Tag" :help ""))
	#("feConvolveMatrix" 0 1 (:annotation "Tag" :help ""))
	#("feDiffuseLighting" 0 1 (:annotation "Tag" :help ""))
	#("feDisplacementMap" 0 1 (:annotation "Tag" :help ""))
	#("feDistantLight" 0 1 (:annotation "Tag" :help ""))
	#("feDropShadow" 0 1 (:annotation "Tag" :help ""))
	#("feFlood" 0 1 (:annotation "Tag" :help ""))
	#("feFuncA" 0 1 (:annotation "Tag" :help ""))
	#("feFuncB" 0 1 (:annotation "Tag" :help ""))
	#("feFuncG" 0 1 (:annotation "Tag" :help ""))
	#("feFuncR" 0 1 (:annotation "Tag" :help ""))
	#("feGaussianBlur" 0 1 (:annotation "Tag" :help ""))
	#("feImage" 0 1 (:annotation "Tag" :help ""))
	#("feMerge" 0 1 (:annotation "Tag" :help ""))
	#("feMergeNode" 0 1 (:annotation "Tag" :help ""))
	#("feMorphology" 0 1 (:annotation "Tag" :help ""))
	#("feOffset" 0 1 (:annotation "Tag" :help ""))
	#("fePointLight" 0 1 (:annotation "Tag" :help ""))
	#("feSpecularLighting" 0 1 (:annotation "Tag" :help ""))
	#("feSpotLight" 0 1 (:annotation "Tag" :help ""))
	#("feTile" 0 1 (:annotation "Tag" :help ""))
	#("feTurbulence" 0 1 (:annotation "Tag" :help ""))
	#("filter" 0 1 (:annotation "Tag" :help ""))
	#("font-face-format" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("font-face-name" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("font-face-src" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("font-face-uri" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("font-face" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("font> Deprecate" 0 1 (:annotation "Tag" :help ""))
	#("foreignObject" 0 1 (:annotation "Tag" :help ""))
	#("g" 0 1 (:annotation "Tag" :help ""))
	#("glyph" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("glyphRef" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("hkern" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("image" 0 1 (:annotation "Tag" :help ""))
	#("line" 0 1 (:annotation "Tag" :help ""))
	#("linearGradient" 0 1 (:annotation "Tag" :help ""))
	#("marker" 0 1 (:annotation "Tag" :help ""))
	#("mask" 0 1 (:annotation "Tag" :help ""))
	#("metadata" 0 1 (:annotation "Tag" :help ""))
	#("missing-glyph" 0 1 (:annotation "Deprecate - Tag" :help ""))
	#("mpath" 0 1 (:annotation "Tag" :help ""))
	#("path" 0 1 (:annotation "Tag" :help ""))
	#("pattern" 0 1 (:annotation "Tag" :help ""))
	#("polygon" 0 1 (:annotation "Tag" :help ""))
	#("polyline" 0 1 (:annotation "Tag" :help ""))
	#("radialGradient" 0 1 (:annotation "Tag" :help ""))
	#("rect" 0 1 (:annotation "Tag" :help ""))
	#("script" 0 1 (:annotation "Tag" :help ""))
	#("set" 0 1 (:annotation "Tag" :help ""))
	#("stop" 0 1 (:annotation "Tag" :help ""))
	#("style" 0 1 (:annotation "Tag" :help ""))
	#("svg" 0 1 (:annotation "Tag" :help ""))
	#("switch" 0 1 (:annotation "Tag" :help ""))
	#("symbol" 0 1 (:annotation "Tag" :help ""))
	#("text" 0 1 (:annotation "Tag" :help ""))
	#("textPath" 0 1 (:annotation "Tag" :help ""))
	#("title" 0 1 (:annotation "Tag" :help ""))
	#("tref" 0 1 (:annotation "Deprecated - Tag" :help ""))
	#("tspan" 0 1 (:annotation "Tag" :help ""))
	#("use" 0 1 (:annotation "Tag" :help ""))
	#("view" 0 1 (:annotation "Tag" :help ""))
	#("vkern" 0 1 (:annotation "Deprecated - Tag" :help ""))
	))

(defconst attr-completions
  '(
	#("accent-height" 0 1 (:annotation "Deprecated - Attr" :help ""))
	#("accumulate" 0 1 (:annotation "Attr" :help ""))
	#("additive" 0 1 (:annotation "Attr" :help ""))
	#("alignment-baseline" 0 1 (:annotation "Attr" :help ""))
	#("alphabetic" 0 1 (:annotation "Deprecated - Attr" :help ""))
	#("amplitude" 0 1 (:annotation "Attr" :help ""))
	#("arabic-form" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("ascent" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("attributeName" 0 1 (:annotation "Attr" :help ""))
	#("attributeType" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("azimuth" 0 1 (:annotation "Attr" :help ""))
	#("baseFrequency" 0 1 (:annotation "Attr" :help ""))
	#("baseline-shift" 0 1 (:annotation "Attr" :help ""))
	#("baseProfile" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("bbox" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("begin" 0 1 (:annotation "Attr" :help ""))
	#("bias" 0 1 (:annotation "Attr" :help ""))
	#("by" 0 1 (:annotation "Attr" :help ""))
	#("calcMode" 0 1 (:annotation "Attr" :help ""))
	#("cap-height" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("class" 0 1 (:annotation "Attr" :help ""))
	#("clip" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("clip-path" 0 1 (:annotation "Attr" :help ""))
	#("clip-rule" 0 1 (:annotation "Attr" :help ""))
	#("clipPathUnits" 0 1 (:annotation "Attr" :help ""))
	#("color" 0 1 (:annotation "Attr" :help ""))
	#("color-interpolation" 0 1 (:annotation "Attr" :help ""))
	#("color-interpolation-filters" 0 1 (:annotation "Attr" :help ""))
	#("cursor" 0 1 (:annotation "Attr" :help ""))
	#("cx" 0 1 (:annotation "Attr" :help ""))
	#("cy" 0 1 (:annotation "Attr" :help ""))
	#("d" 0 1 (:annotation "Attr" :help ""))
	#("data-" 0 1 (:annotation "Attr" :help ""))
	#("decoding" 0 1 (:annotation "Attr" :help ""))
	#("descent" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("diffuseConstant" 0 1 (:annotation "Attr" :help ""))
	#("direction" 0 1 (:annotation "Attr" :help ""))
	#("display" 0 1 (:annotation "Attr" :help ""))
	#("divisor" 0 1 (:annotation "Attr" :help ""))
	#("dominant-baseline" 0 1 (:annotation "Attr" :help ""))
	#("dur" 0 1 (:annotation "Attr" :help ""))
	#("dx" 0 1 (:annotation "Attr" :help ""))
	#("dy" 0 1 (:annotation "Attr" :help ""))
	#("edgeMode" 0 1 (:annotation "Attr" :help ""))
	#("elevation" 0 1 (:annotation "Attr" :help ""))
	#("end" 0 1 (:annotation "Attr" :help ""))
	#("exponent" 0 1 (:annotation "Attr" :help ""))
	#("fill" 0 1 (:annotation "Attr" :help ""))
	#("fill-opacity" 0 1 (:annotation "Attr" :help ""))
	#("fill-rule" 0 1 (:annotation "Attr" :help ""))
	#("filter" 0 1 (:annotation "Attr" :help ""))
	#("filterUnits" 0 1 (:annotation "Attr" :help ""))
	#("flood-color" 0 1 (:annotation "Attr" :help ""))
	#("flood-opacity" 0 1 (:annotation "Attr" :help ""))
	#("font-family" 0 1 (:annotation "Attr" :help ""))
	#("font-size" 0 1 (:annotation "Attr" :help ""))
	#("font-size-adjust" 0 1 (:annotation "Attr" :help ""))
	#("font-stretch" 0 1 (:annotation "Attr" :help ""))
	#("font-style" 0 1 (:annotation "Attr" :help ""))
	#("font-variant" 0 1 (:annotation "Attr" :help ""))
	#("font-weight" 0 1 (:annotation "Attr" :help ""))
	#("fr" 0 1 (:annotation "Attr" :help ""))
	#("from" 0 1 (:annotation "Attr" :help ""))
	#("fx" 0 1 (:annotation "Attr" :help ""))
	#("fy" 0 1 (:annotation "Attr" :help ""))
	#("g1" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("g2" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("glyph-name" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("glyph-orientation-horizontal" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("glyph-orientation-vertical" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("gradientTransform" 0 1 (:annotation "Attr" :help ""))
	#("gradientUnits" 0 1 (:annotation "Attr" :help ""))
	#("hanging" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("height" 0 1 (:annotation "Attr" :help ""))
	#("horiz-adv-x" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("horiz-origin-x" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("horiz-origin-y" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("href" 0 1 (:annotation "Attr" :help ""))
	#("id" 0 1 (:annotation "Attr" :help ""))
	#("ideographic" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("image-rendering" 0 1 (:annotation "Attr" :help ""))
	#("in" 0 1 (:annotation "Attr" :help ""))
	#("in2" 0 1 (:annotation "Attr" :help ""))
	#("intercept" 0 1 (:annotation "Attr" :help ""))
	#("k" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("k1" 0 1 (:annotation "Attr" :help ""))
	#("k2" 0 1 (:annotation "Attr" :help ""))
	#("k3" 0 1 (:annotation "Attr" :help ""))
	#("k4" 0 1 (:annotation "Attr" :help ""))
	#("kernelMatrix" 0 1 (:annotation "Attr" :help ""))
	#("kernelUnitLength" 0 1 (:annotation "Attr" :help ""))
	#("keyPoints" 0 1 (:annotation "Attr" :help ""))
	#("keySplines" 0 1 (:annotation "Attr" :help ""))
	#("keyTimes" 0 1 (:annotation "Attr" :help ""))
	#("lang" 0 1 (:annotation "Attr" :help ""))
	#("lengthAdjust" 0 1 (:annotation "Attr" :help ""))
	#("letter-spacing" 0 1 (:annotation "Attr" :help ""))
	#("lighting-color" 0 1 (:annotation "Attr" :help ""))
	#("limitingConeAngle" 0 1 (:annotation "Attr" :help ""))
	#("marker-end" 0 1 (:annotation "Attr" :help ""))
	#("marker-mid" 0 1 (:annotation "Attr" :help ""))
	#("marker-start" 0 1 (:annotation "Attr" :help ""))
	#("markerHeight" 0 1 (:annotation "Attr" :help ""))
	#("markerUnits" 0 1 (:annotation "Attr" :help ""))
	#("markerWidth" 0 1 (:annotation "Attr" :help ""))
	#("mask" 0 1 (:annotation "Attr" :help ""))
	#("maskContentUnits" 0 1 (:annotation "Attr" :help ""))
	#("maskUnits" 0 1 (:annotation "Attr" :help ""))
	#("mathematical" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("max" 0 1 (:annotation "Attr" :help ""))
	#("media" 0 1 (:annotation "Attr" :help ""))
	#("method Experimental" 0 1 (:annotation "Attr" :help ""))
	#("min" 0 1 (:annotation "Attr" :help ""))
	#("mode" 0 1 (:annotation "Attr" :help ""))
	#("name" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("numOctaves" 0 1 (:annotation "Attr" :help ""))
	#("opacity" 0 1 (:annotation "Attr" :help ""))
	#("operator" 0 1 (:annotation "Attr" :help ""))
	#("order" 0 1 (:annotation "Attr" :help ""))
	#("orient" 0 1 (:annotation "Attr" :help ""))
	#("orientation" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("origin" 0 1 (:annotation "Attr" :help ""))
	#("overflow" 0 1 (:annotation "Attr" :help ""))
	#("overline-position" 0 1 (:annotation "Attr" :help ""))
	#("overline-thickness" 0 1 (:annotation "Attr" :help ""))
	#("paint-order" 0 1 (:annotation "Attr" :help ""))
	#("panose-1" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("path" 0 1 (:annotation "Attr" :help ""))
	#("pathLength" 0 1 (:annotation "Attr" :help ""))
	#("patternContentUnits" 0 1 (:annotation "Attr" :help ""))
	#("patternTransform" 0 1 (:annotation "Attr" :help ""))
	#("patternUnits" 0 1 (:annotation "Attr" :help ""))
	#("pointer-events" 0 1 (:annotation "Attr" :help ""))
	#("points" 0 1 (:annotation "Attr" :help ""))
	#("pointsAtX" 0 1 (:annotation "Attr" :help ""))
	#("pointsAtY" 0 1 (:annotation "Attr" :help ""))
	#("pointsAtZ" 0 1 (:annotation "Attr" :help ""))
	#("preserveAlpha" 0 1 (:annotation "Attr" :help ""))
	#("preserveAspectRatio" 0 1 (:annotation "Attr" :help ""))
	#("primitiveUnits" 0 1 (:annotation "Attr" :help ""))
	#("r" 0 1 (:annotation "Attr" :help ""))
	#("radius" 0 1 (:annotation "Attr" :help ""))
	#("refX" 0 1 (:annotation "Attr" :help ""))
	#("refY" 0 1 (:annotation "Attr" :help ""))
	#("repeatCount" 0 1 (:annotation "Attr" :help ""))
	#("repeatDur" 0 1 (:annotation "Attr" :help ""))
	#("requiredFeatures" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("restart" 0 1 (:annotation "Attr" :help ""))
	#("result" 0 1 (:annotation "Attr" :help ""))
	#("rotate Experimental" 0 1 (:annotation "Attr" :help ""))
	#("rx" 0 1 (:annotation "Attr" :help ""))
	#("ry" 0 1 (:annotation "Attr" :help ""))
	#("scale" 0 1 (:annotation "Attr" :help ""))
	#("seed" 0 1 (:annotation "Attr" :help ""))
	#("shape-rendering" 0 1 (:annotation "Attr" :help ""))
	#("side Experimental" 0 1 (:annotation "Attr" :help ""))
	#("slope" 0 1 (:annotation "Attr" :help ""))
	#("spacing" 0 1 (:annotation "Attr" :help ""))
	#("specularConstant" 0 1 (:annotation "Attr" :help ""))
	#("specularExponent" 0 1 (:annotation "Attr" :help ""))
	#("spreadMethod" 0 1 (:annotation "Attr" :help ""))
	#("startOffset" 0 1 (:annotation "Attr" :help ""))
	#("stdDeviation" 0 1 (:annotation "Attr" :help ""))
	#("stemh" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("stemv" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("stitchTiles" 0 1 (:annotation "Attr" :help ""))
	#("stop-color" 0 1 (:annotation "Attr" :help ""))
	#("stop-opacity" 0 1 (:annotation "Attr" :help ""))
	#("strikethrough-position" 0 1 (:annotation "Attr" :help ""))
	#("strikethrough-thickness" 0 1 (:annotation "Attr" :help ""))
	#("string" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("stroke" 0 1 (:annotation "Attr" :help ""))
	#("stroke-dasharray" 0 1 (:annotation "Attr" :help ""))
	#("stroke-dashoffset" 0 1 (:annotation "Attr" :help ""))
	#("stroke-linecap" 0 1 (:annotation "Attr" :help ""))
	#("stroke-linejoin" 0 1 (:annotation "Attr" :help ""))
	#("stroke-miterlimit" 0 1 (:annotation "Attr" :help ""))
	#("stroke-opacity" 0 1 (:annotation "Attr" :help ""))
	#("stroke-width" 0 1 (:annotation "Attr" :help ""))
	#("style" 0 1 (:annotation "Attr" :help ""))
	#("surfaceScale" 0 1 (:annotation "Attr" :help ""))
	#("crossorigin" 0 1 (:annotation "Attr" :help ""))
	#("systemLanguage" 0 1 (:annotation "Attr" :help ""))
	#("tabindex" 0 1 (:annotation "Attr" :help ""))
	#("tableValues" 0 1 (:annotation "Attr" :help ""))
	#("target" 0 1 (:annotation "Attr" :help ""))
	#("targetX" 0 1 (:annotation "Attr" :help ""))
	#("targetY" 0 1 (:annotation "Attr" :help ""))
	#("text-anchor" 0 1 (:annotation "Attr" :help ""))
	#("text-decoration" 0 1 (:annotation "Attr" :help ""))
	#("text-rendering" 0 1 (:annotation "Attr" :help ""))
	#("textLength" 0 1 (:annotation "Attr" :help ""))
	#("to" 0 1 (:annotation "Attr" :help ""))
	#("transform" 0 1 (:annotation "Attr" :help ""))
	#("transform-origin" 0 1 (:annotation "Attr" :help ""))
	#("type" 0 1 (:annotation "Attr" :help ""))
	#("u1" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("u2" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("underline-position" 0 1 (:annotation "Attr" :help ""))
	#("underline-thickness" 0 1 (:annotation "Attr" :help ""))
	#("unicode" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("unicode-bidi" 0 1 (:annotation "Attr" :help ""))
	#("unicode-range" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("units-per-em" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("v-alphabetic" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("v-hanging" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("v-ideographic" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("v-mathematical" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("values" 0 1 (:annotation "Attr" :help ""))
	#("vector-effect" 0 1 (:annotation "Attr" :help ""))
	#("version" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("vert-adv-y" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("vert-origin-x" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("vert-origin-y" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("viewBox" 0 1 (:annotation "Attr" :help ""))
	#("visibility" 0 1 (:annotation "Attr" :help ""))
	#("width" 0 1 (:annotation "Attr" :help ""))
	#("widths" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("word-spacing" 0 1 (:annotation "Attr" :help ""))
	#("writing-mode" 0 1 (:annotation "Attr" :help ""))
	#("x" 0 1 (:annotation "Attr" :help ""))
	#("x-height" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("x1" 0 1 (:annotation "Attr" :help ""))
	#("x2" 0 1 (:annotation "Attr" :help ""))
	#("xChannelSelector" 0 1 (:annotation "Attr" :help ""))
	#("xlink:arcrole" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("xlink:href" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("xlink:show" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("xlink:title" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("xlink:type" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("xml:lang" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("xml:space" 0 1 (:annotation "Depricated - Attr" :help ""))
	#("y" 0 1 (:annotation "Attr" :help ""))
	#("y1" 0 1 (:annotation "Attr" :help ""))
	#("y2" 0 1 (:annotation "Attr" :help ""))
	#("yChannelSelector" 0 1 (:annotation "Attr" :help ""))
	#("z" 0 1 (:annotation "Attr" :help ""))
	#("zoomAndPan" 0 1 (:annotation "Depricated - Attr" :help ""))
	))

(defvar company-svg--current-context "")

(defun get-completions (context prefix)
  (cl-remove-if-not (lambda (c) (string-prefix-p prefix c))
					(cond
					 ((string= context "<") tag-completions)
					 ((string-suffix-p "\"" context) nil)
					 ((and (> (length context) 1) (string-prefix-p "<" context)) attr-completions)
					 (t nil))))

(defun company-svg-annotation (s)
  (format " %s" (get-text-property 0 :annotation s)))

(defun company-svg-meta (s)
  (get-text-property 0 :help s))

(defun company-svg (command &optional arg &rest ignored)
  (interactive (list 'interactive))
  (cl-case command
	(interactive (company-begin-backend 'company-svg))
	(prefix (when (looking-back "\\([<]*?[^</>]*?\\)\\([!&]?[a-zA-Z1-6]+\\)" 50 t)
			  (setq company-svg--current-context (match-string 1))
			  ;; (message ":%s:%s:" company-svg--current-context (match-string 2))
			  (match-string 2)))
	(candidates (get-completions company-svg--current-context arg))
	(meta (company-svg-meta arg))
	(annotation (company-svg-annotation arg))
	(post-completion (when (string= (company-svg-annotation arg) " Attr")
					   ;; (message "post-completion:%s" arg)
					   (insert "=\"\"")
					   (backward-char 1)))
	(kind t)))

(provide 'company-svg)
