(require 'yasnippet)

(yas-define-snippets 'mhtml-mode '(
				   ("hx-boost" "hx-boost=\"$0\"" "htmx")
				   ("hx-confirm" "hx-confirm=\"$0\"" "htmx")
				   ("hx-delete" "hx-delete=\"$0\"" "htmx")
				   ("hx-disable" "hx-disable=\"$0\"" "htmx")
				   ("hx-disable-elt" "hx-disable-elt=\"$0\"" "htmx")
				   ("hx-disinherit" "hx-disinherit=\"$0\"" "htmx")
				   ("hx-ext" "hx-ext=\"$0\"" "htmx")
				   ("hx-encoding" "hx-encoding=\"$0\"" "htmx")
				   ("hx-get" "hx-get=\"$0\"" "htmx")
				   ("hx-header" "hx-header=\"$0\"" "htmx")
				   ("hx-history" "hx-history=\"$0\"" "htmx")
				   ("hx-history-elt" "hx-history-elt=\"$0\"" "htmx")
				   ("hx-include" "hx-include=\"$0\"" "htmx")
				   ("hx-indicator" "hx-indicator=\"$0\"" "htmx")
				   ("hx-put" "hx-put=\"$0\"" "htmx")
				   ("hx-push-url" "hx-push-url=\"$0\"" "htmx")
				   ("hx-post" "hx-post=\"$0\"" "htmx")
				   ("hx-patch" "hx-patch=\"$0\"" "htmx")
				   ("hx-params" "hx-params=\"$0\"" "htmx")
				   ("hx-preserve" "hx-preserve=\"$0\"" "htmx")
				   ("hx-prompt" "hx-prompt=\"$0\"" "htmx")
				   ("hx-replace-url" "hx-replace-url=\"$0\"" "htmx")
				   ("hx-request" "hx-request=\"$0\"" "htmx")
				   ("hx-select" "hx-select=\"$0\"" "htmx")
				   ("hx-select-oob" "hx-select=\"$0\"" "htmx")
				   ("hx-sse" "hx-sse=\"$0\"" "htmx")
				   ("hx-swap" "hx-swap=\"$0\"" "htmx")
				   ("hx-swap-oob" "hx-swap-oob=\"$0\"" "htmx")
				   ("hx-sync" "hx-sync=\"$0\"" "htmx")
				   ("hx-on" "hx-on=\"$0\"" "htmx")
				   ("hx-on:click" "hx-on:click=\"$0\"" "htmx")
				   ("hx-on:htmx:validation:validate" "hx-on:htmx:validation:validate=\"$0\"" "htmx")
				   ("hx-on:htmx:config-request" "hx-on:htmx:config-request=\"$0\"" "htmx")
				   ("hx-target" "hx-target=\"$0\"" "htmx")
				   ("hx-trigger" "hx-trigger=\"$0\"" "htmx")
				   ("hx-encoding" "hx-encoding=\"$0\"" "htmx")
				   ("hx-ws" "hx-ws=\"$0\"" "htmx")
				   ("hx-vals" "hx-vals=\"$0\"" "htmx")
				   ("hx-validate" "hx-validate=\"$0\"" "htmx")
				   ))

(provide 'company-htmx)
