# -*- mode: snippet -*-
# name: dockerfile-django
# key: dockerfile-django
# expand-env: ((yas-indent-line 'fixed))
# --
FROM python:latest
ENV PYTHONUNBUFFERED 1
RUN mkdir /app
WORKDIR /app
COPY requirements.txt /app
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . /app
EXPOSE 8000
CMD [ "./manage.py", "runserver", "0.0.0.0:8000" ]$0